[package]
authors = ["Ingvar Stepanyan <me@rreverser.com>"]
name = "serde-xml-rs"
version = "0.1.0"

[dependencies]
log = "0.3.6"
serde = "0.9.7"
xml-rs = "0.3.6"

[dev-dependencies]
serde_derive = "0.9.7"
